name: comparer
description: A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
version: 2.0.1
repository: https://github.com/mit-73/comparer
issue_tracker: https://github.com/mit-73/comparer/issues
homepage: https://github.com/mit-73/comparer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.3

flutter:
